name: Python Script Workflow

on:
  push:
    branches:
      - suyashgaonkar-issue-901

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.12'
      
      - name: check pip version
        run: python3 -m pip --version